### PR TITLE
Update to newest TurboReg_.java

### PR DESCRIPTION
**Pull request by cwood1967**
I contacted the author of TurboReg_.java, and here are the changes he wants to see:

I have a couple of objections, which I believe you can easily lift.
1) It would certainly be best if you take as base distribution the latest one, which is available here: http://bigwww.epfl.ch/thevenaz/turboreg/
2) Exhaustively identify every one of your modifications in the source code with a comment where your name appears, possibly with a date, so that it becomes easy to distinguish what you did change to the standard version, and when.
3) Amend the header-like part of the source code so that it is clear that this is a branch of the source code I maintain.

I incorporated the latest turboreg source, identified my changes, and altered the header.

Here is Philippe's permission to go ahead:

> Dear Christopher Woods,
> 
> Thank you for your response. I have made the changes that you indicated, you can look at them at:
> https://github.com/cwood1967/TurboReg
> Please let me know if this is acceptable.
> 
> You have my green light!
> 
> Sincerely Yours,
> P. Thévenaz.
> # 
> 
> P. Thévenaz
> EPFL/STI/IMT-LS/LIB/BM.4.137
> Station 17
> CH-1015 Lausanne VD
> Switzerland

Thanks
Chris

### CODE REVIEW

**Comment by ctrueden** [comment]
@cwood1967 How do you feel about maintaining this fork of TurboReg, in general? You could take on whichever roles at http://imagej.net/Team seem feasible to you. I have to admit that it makes me nervous to host this quasi-sanctioned fork of TurboReg here in the Fiji organization, when the project is not open source, and we have been instructed to keep it based on his latest version, which the author himself does not use Git to track.

**Comment by imagejan** [comment]
@cwood1967 Your commit to update the original source (https://github.com/fiji/TurboReg/pull/4/commits/b1426441b8cc387b7a9b822ccf1b22d19f5cb2ac) is quite huge, you might have introduced some unwanted formatting changes.

I just imported the source from http://bigwww.epfl.ch/thevenaz/turboreg/ and committed it in a new topic branch [`update-original-source`](https://github.com/imagejan/TurboReg/commits/update-original-source) here: https://github.com/imagejan/TurboReg/commit/bad98cc8c6e9623db8944f1da1feddff14363983

This commit also mentions Philippe Thévenaz as the original author.

May I ask you that you rebase your changes on this commit, so that the git history stays clean and readable?

**Comment by ctrueden** [comment]
@cwood1967 Any comments r.e. your willingness to act as maintainer?

**Comment by cwood1967** [comment]
@ctrueden I am willing to be a maintainer. I am still working on my git skills, so there might be some questions....

@imagejan what do you mean by huge? I included the latest source from epfl in my pull request, do you want me to redo that?
Did I make to many commits of trivial changes?
I will gladly do a rebase to clean it up, I might have some questions about how to do that.

**Comment by ctrueden** [comment]
> I am willing to be a maintainer.

Awesome. Did you read over the [team roles](http://imagej.net/Team)? Which ones are you willing to commit to?

> I am still working on my git skills, so there might be some questions....

No problem. I am very happy to help train you.

> what do you mean by huge? I included the latest source from epfl in my pull request, do you want me to redo that?

In my opinion, the very first commit of this topic branch should be the update to the latest canonical version of TurboReg. Then subsequent commits should stack on your changes, each clearly bracketed by your initials and datestamp of the change (even though Git already keeps track of this, it will ease the original author's mind to do this, I guess).

> Did I make to many commits of trivial changes?

I am always in favor of more granular changes, as long as each changeset still compiles with passing tests. This eases debugging, and improves human understanding of the history. See also the [SCM history](http://imagej.net/Coding_style#SCM_history) section on the wiki.

> I will gladly do a rebase to clean it up, I might have some questions about how to do that.

Please read the guides linked from: http://imagej.net/Git#Rewriting_history

**Comment by cwood1967** [comment]
I would be willing to go up to developer, but with the license status that might not be a proper role.
So, I guess everything from contributor up to and including debugger.

**Comment by ctrueden** [comment]
> I would be willing to go up to developer, but with the license status that might not be a proper role. So, I guess everything from contributor up to and including debugger.

Sounds good. Note that the project roles describe responsibility for this _fork_ of the project, not the _original_ project. So "Developer" would imply that you are actively developing features for the Fiji fork. I think it is fine for you _not_ to formally take the "developer" role; this does not preclude you from occasionally adding features as your time allows—it simply means you are not promising anything with respect to new features.

Note that the medium-term plan is to split this component, along with all BIG component forks, to their own BIG update site. That will help the core Fiji distribution break free of the licensing issues, while still providing these very useful components to the user community.

**Comment by imagejan** [comment]
> what do you mean by huge? I included the latest source from epfl in my pull request, do you want me to redo that?

@cwood1967 I just wanted to say that your commit reported the whole file to be changed, see the diff: https://github.com/fiji/TurboReg/pull/4/commits/b1426441b8cc387b7a9b822ccf1b22d19f5cb2ac

> 9,432 additions, 9,358 deletions

whereas when I compared the current master with the version from http://bigwww.epfl.ch/thevenaz/turboreg/ I see only:

> 792 additions and 728 deletions.

as seen here: https://github.com/imagejan/TurboReg/commit/bad98cc8c6e9623db8944f1da1feddff14363983

I guess you might have committed a file that changed the line breaks in every single line from Windows- to Linux-style or vice versa, resulting in a diff that effectively hides the actual changes.

**Comment by cwood1967** [comment]
There was an issue of CRLF line endings that caused the huge commit. I fixed that so only the real changes are shown when doing a diff. In doing this I had to redo all of the other commits on top of this, so the history now has the same thing three times. Is there any way I can clean that up?

**Comment by imagejan** [comment]
> Is there any way I can clean that up?

You can amend commits and force-push to the branch on your fork (which should preferably be a topic branch and _not_ `master`):

`git push <fork-repo> <branch-name> -f`

See also [topic branch editing](http://imagej.net/Git_topic_branches#Advanced_topic_branch_editing_.28AKA_rebase_on_drugs.29).

**Comment by cwood1967** [comment]
@imagejan and @ctrueden 
I have a clean branch that now starts with commit c173d44 and only has my changes:
https://github.com/cwood1967/TurboReg/commits/clean

Can this replace what is in the master branch, or would that be bad form?
Chris

**Comment by imagejan** [comment]
@cwood1967 Sorry for the delay in reply!

> Can this replace what is in the master branch, or would that be bad form?

While you can freely rewrite the history branch on your own fork, it's a bad idea to do so in the parent repository, because others might have checked out the commits you're overwriting, which will break the consistent state of their repos.

May I suggest that you rebuild again on top of https://github.com/fiji/TurboReg/commits/master?

You can also take https://github.com/imagejan/TurboReg/commits/update-original-source, or cherry-pick https://github.com/imagejan/TurboReg/commit/bad98cc8c6e9623db8944f1da1feddff14363983 which includes Philippe Thévenaz as **author** of the commit (while technically I am the committer).

---

Regarding the change of the ResultsTable: Philippe changed the results table to show with the correct name "Results" to be the default ImageJ1 results table. I think this is still useful because it allows to collect the results from several runs in the same table. Is there a specific reason why you want TurboReg use its own `ResultsTable`?

---

It would be great, @cwood1967, if you can be the maintainer of this plugin. I think it is very useful, and currently nothing exists yet to replace its functionality in `imagej-ops` (where the algorithm would ideally go in the long term, do you agree, @ctrueden ?).

Let me know how it goes and I'll rebase https://github.com/fiji/TurboReg/pull/5 eventually.

**Comment by cwood1967** [comment]
@imagejan 

> Regarding the change of the ResultsTable: Philippe changed the results table to show with the correct name "Results" to be the default ImageJ1 results table. I think this is still useful because it allows to collect the results from several runs in the same table. Is there a specific reason why you want TurboReg use its own ResultsTable?

We were writing a macro that uses StackReg and writing results to a table. Running StackReg/TurboReg reset the table so our results were lost.

> May I suggest that you rebuild again on top of https://github.com/fiji/TurboReg/commits/master?

Can I just do a rebase or does it need something more involved.

**Comment by cwood1967** [comment]
I am closing this pull request and opening a new one that follows the suggestion of @imagejan to rebuild on top of https://github.com/fiji/TurboReg/commits/master?

The new rebase is at https://github.com/cwood1967/TurboReg/tree/cleanrebase

**Pull request closed without merging**
